services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_pass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: